# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Thai Tran
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_codegen
mimetype: ''
mimetype_name: ''
project_short_description: JupyterLab extension that can generate code using GPT-4
    (similar to ChatGPT's Code Interpreter)
python_name: jupyterlab_codegen
repository: https://github.com/thaitran/JupyterLab-CodeGen
test: true
viewer_name: ''

